const { MongoClient } = require("mongodb");

const MONGODB_URI = "mongodb://127.0.0.1:27017";
const DB_NAME = "ecommerce";

const products = [
  // ELECTRONICS
  {
    product_id: "P2210",
    name: "Ultra Smartphone Pro Max 5G",
    category: "Electronics",
    price: 289.0,
    status: "active",
    stock: 45,
    rating: 4.8,
    reviews_count: 124,
    image: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=800&q=80",
    screen_size: "6.7 inch OLED 120Hz",
    warranty: "1 Year Official Distributor",
    description: "Flagship AMOLED display with high-efficiency 5G modem, AI computational photography, and fast charge.",
  },
  {
    product_id: "P2211",
    name: "Noise-Cancelling Wireless Earbuds Pro",
    category: "Electronics",
    price: 65.0,
    status: "active",
    stock: 80,
    rating: 4.7,
    reviews_count: 89,
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80",
    screen_size: "Touch Sensor Interface",
    warranty: "6 Months Replacement",
    description: "Active noise cancellation up to 42dB with transparency mode and water-resistant nano-coating.",
  },
  {
    product_id: "P2212",
    name: "Curved 4K Ultra-Wide Monitor 34\"",
    category: "Electronics",
    price: 420.0,
    status: "active",
    stock: 18,
    rating: 4.9,
    reviews_count: 53,
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80",
    screen_size: "34 inch 1500R Curved 4K",
    warranty: "2 Years Manufacturer",
    description: "Immersive panoramic display with 99% sRGB color accuracy, USB-C 90W power delivery, and built-in KVM switch.",
  },
  {
    product_id: "P2213",
    name: "Fitness Smartwatch GPS Pro Sapphire",
    category: "Electronics",
    price: 85.0,
    status: "active",
    stock: 65,
    rating: 4.6,
    reviews_count: 72,
    image: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=800&q=80",
    screen_size: "1.43 inch AMOLED Sapphire",
    warranty: "1 Year Official Distributor",
    description: "Multi-band GPS tracking, continuous SpO2 heart-rate telemetry, and 14-day battery life.",
  },
  {
    product_id: "P2214",
    name: "Mechanical Gaming Keyboard RGB (Hot-Swap)",
    category: "Electronics",
    price: 54.0,
    status: "active",
    stock: 50,
    rating: 4.8,
    reviews_count: 64,
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80",
    screen_size: "75% Compact Layout",
    warranty: "1 Year Warranty",
    description: "Factory-lubed linear switches with sound-dampening silicone gasket and RGB backlighting.",
  },
  {
    product_id: "P2215",
    name: "Ultra Fast-Charging Power Bank 20,000mAh 65W",
    category: "Electronics",
    price: 36.0,
    status: "active",
    stock: 110,
    rating: 4.9,
    reviews_count: 145,
    image: "https://images.unsplash.com/photo-1609592424364-77be1c028ba4?auto=format&fit=crop&w=800&q=80",
    screen_size: "Smart Digital Power Display",
    warranty: "6 Months Replacement",
    description: "65W USB-C Power Delivery charges laptops and smartphones simultaneously.",
  },
  {
    product_id: "P2216",
    name: "Dual-Band Wi-Fi 6 Gigabit Mesh Router",
    category: "Electronics",
    price: 79.0,
    status: "active",
    stock: 40,
    rating: 4.7,
    reviews_count: 38,
    image: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=800&q=80",
    screen_size: "Dual-Band AX3000",
    warranty: "2 Years Replacement",
    description: "Covers up to 3,000 sq ft with low-latency beamforming antennas.",
  },
  {
    product_id: "P2217",
    name: "Compact 4K Foldable Drone with 3-Axis Gimbal",
    category: "Electronics",
    price: 349.0,
    status: "active",
    stock: 14,
    rating: 4.8,
    reviews_count: 29,
    image: "https://images.unsplash.com/photo-1527977966376-1c8408f9f108?auto=format&fit=crop&w=800&q=80",
    screen_size: "4K 60fps 3-Axis Gimbal",
    warranty: "1 Year Manufacturer",
    description: "Under 249g ultra-lightweight drone with obstacle avoidance and 31-minute flight time.",
  },

  // CLOTHING
  {
    product_id: "P3314",
    name: "Premium Linen Casual Shirt (Summer Edition)",
    category: "Clothing",
    price: 18.5,
    status: "active",
    stock: 120,
    rating: 4.6,
    reviews_count: 67,
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80",
    size: "L",
    colours: ["Navy Blue", "Sand Beige", "Olive"],
    description: "Breathable 100% natural organic linen tailored for tropical climates with reinforced horn-button closure.",
  },
  {
    product_id: "P3315",
    name: "Handwoven Silk Scarf (Takeo Krama Luxe)",
    category: "Clothing",
    price: 32.0,
    status: "active",
    stock: 60,
    rating: 4.9,
    reviews_count: 94,
    image: "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?auto=format&fit=crop&w=800&q=80",
    size: "Free Size (180x60cm)",
    colours: ["Crimson Red", "Royal Indigo", "Emerald Gold"],
    description: "Artisanal handwoven silk from Takeo weavers, featuring authentic heritage patterns with a modern drape.",
  },
  {
    product_id: "P3316",
    name: "Everyday Stretch Chino Pants",
    category: "Clothing",
    price: 24.0,
    status: "active",
    stock: 75,
    rating: 4.5,
    reviews_count: 42,
    image: "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=800&q=80",
    size: "32W x 30L",
    colours: ["Khaki", "Charcoal", "Dark Navy"],
    description: "Comfortable four-way stretch cotton twill designed for versatile office and casual city commuting.",
  },
  {
    product_id: "P3317",
    name: "Organic Cotton Short-Sleeve Resort Shirt",
    category: "Clothing",
    price: 21.0,
    status: "active",
    stock: 90,
    rating: 4.7,
    reviews_count: 58,
    image: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80",
    size: "M",
    colours: ["Palm Leaf Green", "Ivory White"],
    description: "Relaxed Cuban collar cut in pure combed cotton, pre-washed for zero shrinkage and ultra-soft feel.",
  },
  {
    product_id: "P3318",
    name: "Waterproof Commuter Backpack 22L (Laptop Ready)",
    category: "Clothing",
    price: 45.0,
    status: "active",
    stock: 55,
    rating: 4.8,
    reviews_count: 83,
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80",
    size: "22 Litres (16\" Laptop Compartment)",
    colours: ["Matte Black", "Graphite Grey"],
    description: "Weatherproof coated canvas with magnetic quick-release clasps and padded ergonomic shoulder straps.",
  },
  {
    product_id: "P3319",
    name: "Handcrafted Heritage Leather Loafers",
    category: "Clothing",
    price: 58.0,
    status: "active",
    stock: 35,
    rating: 4.9,
    reviews_count: 46,
    image: "https://images.unsplash.com/photo-1533867617858-e7b97e060509?auto=format&fit=crop&w=800&q=80",
    size: "EU 42 (US 9)",
    colours: ["Cognac Brown", "Ebony Black"],
    description: "Full-grain vegetable-tanned leather handcrafted by local cordwainers with cushioned cork insole.",
  },
  {
    product_id: "P3320",
    name: "Breathable Bamboo Fiber Lounge Set",
    category: "Clothing",
    price: 28.0,
    status: "active",
    stock: 65,
    rating: 4.6,
    reviews_count: 39,
    image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80",
    size: "L",
    colours: ["Sage Mist", "Warm Oat"],
    description: "Thermo-regulating natural bamboo viscose two-piece lounge set engineered for hot and humid climates.",
  },
  {
    product_id: "P3321",
    name: "UV-Protection Lightweight Sun Hoodie UPF 50+",
    category: "Clothing",
    price: 19.5,
    status: "active",
    stock: 100,
    rating: 4.7,
    reviews_count: 61,
    image: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80",
    size: "XL",
    colours: ["Glacier Blue", "Stone Grey"],
    description: "UPF 50+ sun protection hooded jacket with thumbholes and fast-drying fabric.",
  },

  // GROCERIES
  {
    product_id: "P0874",
    name: "Battambang Jasmine Fragrant Rice 5kg (Malys Angkor)",
    category: "Groceries",
    price: 4.8,
    status: "active",
    stock: 250,
    rating: 4.9,
    reviews_count: 310,
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=800&q=80",
    weight: "5.0 kg Bag",
    expiry_date: "2027-10-01",
    description: "Award-winning Malys Angkor aromatic long-grain jasmine rice, vacuum-sealed at source in Battambang.",
  },
  {
    product_id: "P0875",
    name: "Kampot Organic Black Pepper 250g (PGI Certified)",
    category: "Groceries",
    price: 7.5,
    status: "active",
    stock: 140,
    rating: 5.0,
    reviews_count: 184,
    image: "https://images.unsplash.com/photo-1599940824399-b87987ceb72a?auto=format&fit=crop&w=800&q=80",
    weight: "250g Glass Jar",
    expiry_date: "2028-04-15",
    description: "Protected Geographical Indication (PGI) certified Kampot peppercorns with intense floral and mint notes.",
  },
  {
    product_id: "P0876",
    name: "Mondulkiri Dark Roast Arabica Beans 500g",
    category: "Groceries",
    price: 9.2,
    status: "active",
    stock: 95,
    rating: 4.8,
    reviews_count: 112,
    image: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&w=800&q=80",
    weight: "500g Foil Valve Bag",
    expiry_date: "2027-08-30",
    description: "High-altitude volcanic soil highland beans roasted in small artisan batches for rich cacao undertones.",
  },
  {
    product_id: "P0877",
    name: "Wild Raw Forest Honey from Koh Kong 500ml",
    category: "Groceries",
    price: 14.0,
    status: "active",
    stock: 70,
    rating: 4.9,
    reviews_count: 89,
    image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=800&q=80",
    weight: "500ml Sealed Glass Bottle",
    expiry_date: "2028-06-15",
    description: "Harvested sustainably by community foragers in the Cardamom Mountains, unprocessed and unfiltered.",
  },
  {
    product_id: "P0878",
    name: "Kampot Fleur de Sel (Flower of Salt) 300g",
    category: "Groceries",
    price: 5.5,
    status: "active",
    stock: 115,
    rating: 4.9,
    reviews_count: 67,
    image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=800&q=80",
    weight: "300g Ceramic Crock",
    expiry_date: "2029-01-01",
    description: "Hand-skimmed delicate salt crystals from solar salt evaporation ponds along the Gulf of Thailand coastline.",
  },
  {
    product_id: "P0879",
    name: "Artisanal Kampong Speu Palm Sugar 500g",
    category: "Groceries",
    price: 3.8,
    status: "active",
    stock: 180,
    rating: 4.8,
    reviews_count: 121,
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80",
    weight: "500g Eco Palm Container",
    expiry_date: "2027-09-20",
    description: "PGI certified natural unrefined golden palm sugar syrup granulated traditionally over wood fires.",
  },
  {
    product_id: "P0880",
    name: "Organic Lemongrass & Ginger Herbal Tea 50 Bags",
    category: "Groceries",
    price: 6.5,
    status: "active",
    stock: 85,
    rating: 4.7,
    reviews_count: 54,
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=800&q=80",
    weight: "150g Biodegradable Box",
    expiry_date: "2027-11-30",
    description: "Refreshing immune-supporting herbal infusion crafted with whole sun-dried lemongrass stalks.",
  },
  {
    product_id: "P0881",
    name: "Roasted Cashew Nuts with Sea Salt 400g (Jumbo M23)",
    category: "Groceries",
    price: 8.5,
    status: "active",
    stock: 130,
    rating: 4.9,
    reviews_count: 165,
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80",
    weight: "400g Foil Seal Tub",
    expiry_date: "2027-07-15",
    description: "Premium jumbo M23 cashew nuts grown in Kampong Cham, slow-roasted with skin on for deep crunch.",
  },
];

async function run() {
  console.log("Connecting to MongoDB...");
  const client = new MongoClient(MONGODB_URI);
  try {
    await client.connect();
    const db = client.db(DB_NAME);
    const col = db.collection("products");

    console.log("Removing outdated products...");
    await col.deleteMany({});

    console.log(`Inserting ${products.length} comprehensive products...`);
    const res = await col.insertMany(products);
    console.log(`Success! Inserted ${res.insertedCount} products into MongoDB.`);

    const count = await col.countDocuments();
    console.log(`Total products in MongoDB collection: ${count}`);
  } catch (err) {
    console.error("MongoDB seed error:", err);
  } finally {
    await client.close();
  }
}

run();
